// src/components/Footer.svelte
<footer>
	<q cite="https://en.wikipedia.org/wiki/Joaquin_Phoenix">
		It takes nothing away from a human to be kind to an animal.
	</q>
	<div class="links">
		<a href="https://github.com/Naerhy" target="_blank">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
			</svg>
		</a>
		<a href="https://www.30millionsdamis.fr" target="_blank">
			<svg
				xmlns="http://www.w3.org/2000/svg"
				width="24"
				height="24"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
			</svg>
		</a>
	</div>
</footer>

<style>
	footer {
		align-items: center;
		background-color: var(--surface-dark);
		color: var(--text-light-default);
		display: flex;
		flex-direction: column;
		padding: 2rem 0;
		row-gap: 0.5rem;
	}

	q {
		color: var(--text-light-subtle);
		font-size: 0.875rem;
		font-style: italic;
		line-height: 1.25rem;
	}

	.links {
		column-gap: 1rem;
		display: flex;
	}

	svg:hover {
		color: var(--highlight);
	}
</style>

// frontend/src/components/Footer.vue
<template>
	<footer>
		<q cite="https://en.wikipedia.org/wiki/Joaquin_Phoenix">
			It takes nothing away from a human to be kind to an animal.
		</q>
		<div class="links">
			<a href="https://github.com/Naerhy" target="_blank">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
				</svg>
			</a>
			<a href="https://www.30millionsdamis.fr" target="_blank">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
				</svg>
			</a>
		</div>
	</footer>
</template>

<style scoped>
	footer {
		align-items: center;
		background-color: #212121;
		color: #f5f5f5;
		display: flex;
		flex-direction: column;
		padding: 1rem 0;
		row-gap: 0.5rem;
	}

	q {
		color: #bdbdbd;
		font-size: 0.875rem;
		font-style: italic;
		line-height: 1.25rem;
	}

	.links {
		column-gap: 1rem;
		display: flex;
	}

	svg:hover {
		color: var(--highlight);
	}
</style>
