// frontend/src/App.vue
<script setup lang="ts">
	import "@fontsource-variable/inter";
	import { onMounted } from "vue";
	import axios from "axios";
	import { requestsBaseUrl } from "./constants";
	import type { Meal } from "./types";
	import Header from "./components/Header.vue";
	import Footer from "./components/Footer.vue";
	import { useMealsStore } from "./stores";

	const mealsStore = useMealsStore();

	onMounted(async () => {
		try {
			const { data: loadedMeals } = await axios.get<Meal[]>(`${requestsBaseUrl}/meals`);
			shuffleMeals(loadedMeals);
			mealsStore.meals = loadedMeals;
			mealsStore.state = "loaded";
		} catch {
			mealsStore.state = "error";
		}
	});

	function shuffleMeals(meals: Meal[]): void {
		for (let i = meals.length - 1; i > 0; i--) {
			let j = Math.floor(Math.random() * (i + 1));
			[meals[i], meals[j]] = [meals[j], meals[i]];
		}
	}
</script>

<template>
	<Header />
	<router-view />
	<Footer />
</template>

<style>
	html {
		--background: #eeeeee;
		--background-dark: #e0e0e0;
		--stroke: #bdbdbd;
		--highlight: #3f51b5;
		--highlight-dark: #3949ab;
		--text-default: #212121;
		--text-subtle: #757575;
		--text-highlight: #f5f5f5;
		background-color: var(--background);
		color: var(--text-default);
		font-family: "Inter Variable", Arial;
	}

	#app {
		display: flex;
		flex-direction: column;
		min-height: 100vh;
		row-gap: 2rem;
	}

	main {
		flex: 1 1 auto;
	}

	h1,
	h2,
	h3,
	h4,
	h5,
	h6,
	.bold {
		font-weight: 700;
	}

	.flex-col {
		display: flex;
		flex-direction: column;
	}

	.input,
	.select {
		border: 1px solid var(--stroke);
		border-radius: 0.375rem;
		padding: 0.25rem 0.5rem;
	}

	.input {
		background-color: var(--background-dark);
	}

	.input::placeholder {
		color: var(--text-subtle);
	}

	.input:focus {
		outline: 2px solid var(--highlight);
	}

	.btn-contained,
	.btn-text {
		border-radius: 0.25rem;
		padding: 0.5rem 0.8rem;
	}

	.btn-contained {
		background-color: var(--highlight);
		color: var(--text-highlight);
	}

	.btn-contained:hover {
		background-color: var(--highlight-dark);
	}

	.btn-text:hover {
		background-color: var(--background-dark);
	}
</style>

// src/App.svelte
<script lang="ts">
	import '@fontsource-variable/inter';
	import { parseJsonRecipe } from "./validate";
	import type { RecipeFN } from "./types";
	import Footer from "./components/Footer.svelte";
	import RecipesList from "./components/RecipesList.svelte";
	import Button from "./components/Button.svelte";
	import RecipeModal from "./components/RecipeModal.svelte";
	import Header from "./components/Header.svelte";

	let focusedRecipeId: RecipeFN | null = null;

	async function loadFiles(): Promise<RecipeFN[]> {
		// no need to wrap into try/catch because Svelte already wraps it when
		// calling it from html
		const files = import.meta.glob("./data/*.json");
		const recipes: RecipeFN[] = [];
		for (const path in files) {
			const filename = path.replace("./data/", "").replace(".json", "");
			const recipe = parseJsonRecipe((await files[path]()).default);
			if (recipe !== null) {
				recipes.push({ filename, ...recipe });
			} else {
				console.warn(`Unable to parse recipe: ${filename}`);
			}
		}
		return recipes;
	}

	function handleClickRecipe(event: any): void {
		focusedRecipeId = event.detail.recipe;
	}
</script>

{#if focusedRecipeId !== null}
<RecipeModal recipe={focusedRecipeId} on:click={() => focusedRecipeId = null} />
{/if}
<Header />
{#await loadFiles() then recipes}
<main class="loaded">
	<RecipesList {recipes} on:clickrecipe={handleClickRecipe} />
</main>
{:catch error}
{@const errMsg = (error instanceof Error && error.message) ? error.message : "unexpected error"}
<main class="error">
	<section>
		<h2>Oops!</h2>
		<p>
			The website encountered an error while trying to load the recipes.<br>
			Reason: {errMsg}.
		</p>
		<Button type="button" on:click={() => location.reload()}>Reload</Button>
	</section>
</main>
{/await}
<Footer />

<style>
	:global(:root) {
		--surface-default: #eeeeee;
		--surface-raised: #f5f5f5;
		--stroke: #e0e0e0;
		--highlight: #3f51b5;
		--highlight-d15: #3949ab;
		--text-default: #212121;
		--text-subtle: #757575;
		--text-highlight: #f5f5f5;
		background-color: var(--surface-default);
		color: var(--text-default);
		font-family: "Inter Variable", Arial;
	}

	:global(#app) {
		display: flex;
		flex-direction: column;
		min-height: 100vh;
		row-gap: 2rem;
	}

	:global(h1, h2, h3, h4, h5, h6) {
		font-weight: 700;
	}

	main {
		flex: 1 1 auto;
	}

	.loaded {
		align-items: flex-start;
		column-gap: 2rem;
		display: flex;
		margin: auto;
		width: 80%;
	}

	.error {
		align-items: center;
		display: flex;
		justify-content: center;
	}

	.error section {
		background-color: var(--surface-raised);
		border: 1px solid var(--stroke);
		border-radius: 0.25rem;
		display: flex;
		flex-direction: column;
		padding: 2rem;
		row-gap: 1rem;
	}

	.error h2 {
		font-size: 2.25rem;
		line-height: 2.5rem;
		text-align: center;
	}
</style>
